import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import { Toaster } from "react-hot-toast";
import ReactQueryClientProvider from "@/provider/ReactQueryClientProvider";

import TenantGuard from "@/guards/TenantGuards";
import TenantNavbar from "@/components/navbar/page";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{
        backgroundColor: "#DDE4D0", // ✅ fix background for html
        margin: 0,
        padding: 0,
      }}
    >
      <body
        style={{
          backgroundColor: "#DDE4D0", // ✅ match with html
          margin: 0,
          padding: 0,
          minHeight: "100vh",
        }}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryClientProvider>
          <Toaster />
          <TenantGuard>
            <TenantNavbar />
            <main className="pt-[80px] flex justify-center items-center min-h-[calc(100vh-30px)]">
              {children}
            </main>
            <Footer />
          </TenantGuard>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
